export enum APP_CODE {
  // Prisma Client Errors
  PRISMA_CLIENT_ERROR = 2001,

  // MongoDB Database Errors
  MONGODB_CONNECTION_ERROR = 2002,
  MONGODB_QUERY_ERROR = 2003,

  // User Model Errors
  USERNAME_ALREADY_EXISTS = 3001,
  REGISTRATION_ALREADY_EXISTS = 3002,
  CPF_ALREADY_EXISTS = 3003,
  EMAIL_ALREADY_EXISTS = 3004,
  INVALID_BIRTHDATE_FORMAT = 3005,
  INVALID_ROLE = 3006,
  USER_NOT_FOUND = 3007,
  USER_STATUS_UPDATE_FAILED = 3008,
  USER_DELETE_FAILED = 3009,
  USER_INCORRECT = 3010,
  INVALID_CPF = 3011,
  INVALID_PHONE = 3012,
  // Guideline Errors
  REFUSED_GUIDELINE = 4000,
  GUIDELINE_NOT_FOUND = 4001,
  INVALID_GUIDELINE_TYPE = 4002,
  GUIDELINE_STATUS_UPDATE_FAILED = 4003,
  GUIDELINE_DELETE_FAILED = 4004,

  // Guideline Accepted Errors
  GUIDELINE_ACCEPTANCE_FAILED = 5001,
  GUIDELINE_ACCEPTANCE_REJECTION_FAILED = 5002,
  GUIDELINE_ACCEPTANCE_UPDATE_FAILED = 5003,
  GUIDELINE_ACCEPTANCE_DELETE_FAILED = 5004,

  // Device Errors
  DEVICE_NOT_FOUND = 6001,
  DEVICE_CREATION_FAILED = 6002,
  DEVICE_UPDATE_FAILED = 6003,
  DEVICE_DELETE_FAILED = 6004,

  // Code Errors
  CODE_NOT_FOUND = 7001,
  INVALID_CODE_TYPE = 7002,
  CODE_GENERATION_FAILED = 7003,
  CODE_VALIDATION_FAILED = 7004,
  CODE_STATUS_UPDATE_FAILED = 7005,
  CODE_DELETE_FAILED = 7006,

  // Fingerprint Verification Errors
  FINGERPRINT_VERIFICATION_FAILED = 8001,

  // Google reCAPTCHA Errors
  RECAPTCHA_FAILED = 8002,

  // RSA Encryption Errors
  RSA_ENCRYPTION_ERROR = 8003,

  // Bcrypt Hashing Errors
  BCRYPT_HASHING_ERROR = 8004,

  // SMTP Email Sending Errors
  EMAIL_SENDING_FAILED = 8005,
}
