export enum APP_STATUS_CODE {
  // Prisma Client Errors
  PRISMA_CLIENT_ERROR = 500,

  // MongoDB Database Errors
  MONGODB_CONNECTION_ERROR = 500,
  MONGODB_QUERY_ERROR = 500,

  // User Model Errors
  USERNAME_ALREADY_EXISTS = 409,
  REGISTRATION_ALREADY_EXISTS = 409,
  CPF_ALREADY_EXISTS = 409,
  INVALID_CPF = 400,
  EMAIL_ALREADY_EXISTS = 409,
  INVALID_BIRTHDATE_FORMAT = 400,
  INVALID_ROLE = 400,
  USER_NOT_FOUND = 404,
  USER_STATUS_UPDATE_FAILED = 500,
  USER_DELETE_FAILED = 500,
  USER_INCORRECT = 403,
  INVALID_PHONE = 400,

  // Guideline Errors
  REFUSED_GUIDELINE = 403,
  GUIDELINE_NOT_FOUND = 404,
  INVALID_GUIDELINE_TYPE = 400,
  GUIDELINE_STATUS_UPDATE_FAILED = 500,
  GUIDELINE_DELETE_FAILED = 500,

  // Guideline Accepted Errors
  GUIDELINE_ACCEPTANCE_FAILED = 500,
  GUIDELINE_ACCEPTANCE_REJECTION_FAILED = 500,
  GUIDELINE_ACCEPTANCE_UPDATE_FAILED = 500,
  GUIDELINE_ACCEPTANCE_DELETE_FAILED = 500,

  // Device Errors
  DEVICE_NOT_FOUND = 404,
  DEVICE_CREATION_FAILED = 500,
  DEVICE_UPDATE_FAILED = 500,
  DEVICE_DELETE_FAILED = 500,

  // Code Errors
  CODE_NOT_FOUND = 404,
  INVALID_CODE_TYPE = 400,
  CODE_GENERATION_FAILED = 500,
  CODE_VALIDATION_FAILED = 400,
  CODE_STATUS_UPDATE_FAILED = 500,
  CODE_DELETE_FAILED = 500,

  // Fingerprint Verification Errors
  FINGERPRINT_VERIFICATION_FAILED = 500,

  // Google reCAPTCHA Errors
  RECAPTCHA_FAILED = 400,

  // RSA Encryption Errors
  RSA_ENCRYPTION_ERROR = 500,

  // Bcrypt Hashing Errors
  BCRYPT_HASHING_ERROR = 500,

  // SMTP Email Sending Errors
  EMAIL_SENDING_FAILED = 500,
}
